### ISSUE TITLE
[Accessibility] Translations

### ISSUE THREAD

**Issue by TtuxX** [jimmyl0l3c/cfg_share_links#28]
Hi there @jimmyl0l3c :)

I would love to translate your app into French.

Would it be possible to have it available for translation into several languages on https://www.transifex.com/nextcloud/nextcloud/translate/ ? :)

Thank you very much in advance !

**Comment by jimmyl0l3c** [comment]
Hi,
sorry for the late answer, I was waiting for my PR to be reviewed. 

The app is now on transifex, but there are several issues with text strings that should be resolved by next sync job.
And I'm waiting for nextcloud-bot to accept invite to repo, so it can update translations.

**Comment by TtuxX** [comment]
Hi @jimmyl0l3c

Great, thank you very much for these pieces of information! :)

I will gladly start to translate it.

Thank you very much!

**Comment by nickvergessen** [comment]
Please grant write access to https://github.com/nextcloud-bot at https://github.com/jimmyl0l3c/cfg_share_links/settings/access
so it has push permissions. If master push is protected and PRs need to be sent, please grant admin access because the bot can not do PRs.

**Comment by nickvergessen** [comment]
> And I'm waiting for nextcloud-bot to accept invite to repo, so it can update translations.

Sorry missed that. Will check who on our side can accept that.

**Comment by nickvergessen** [comment]
We accepted the invite, but it's still failing:
> ERROR: Permission to jimmyl0l3c/cfg_share_links.git denied to nextcloud-bot.
fatal: Could not read from remote repository.

Can you please grant higher permissions as mentioned above?

**Comment by jimmyl0l3c** [comment]
Master is not push protected. Is it fine now? Or where can I grant the bot higher permission?

**Comment by nickvergessen** [comment]
Seems to work now https://github.com/jimmyl0l3c/cfg_share_links/commit/1f0dcf8954ba77d895c2dd6285278b8077d2d07e
